# Generated by Django 2.2.5 on 2020-06-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesubheading',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
