# Generated by Django 2.2.5 on 2020-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200614_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesubheading',
            name='subheading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
